### ISSUE TITLE
优酷视频下载不完全

### ISSUE THREAD

**Issue by jarwin123** [Mickeyto/phpVideos#10]
![default](https://user-images.githubusercontent.com/8475971/52693608-20064500-2fa2-11e9-86d5-48e1110cce54.png)
https://v.youku.com/v_show/id_XNTQwMTgxMTE2.html?spm=a2ha1.12523958.m_4392_c_12696.d_01
这个原视频有24分钟，但是下载后才5分钟
求解决！

**Comment by Mickeyto** [comment]
我今晚看看

**Comment by jarwin123** [comment]
@Mickeyto 你有没有自己的群？我可以添加么？你可以私信给我，谢谢！

**Comment by Mickeyto** [comment]
QQ群：302393963
