### ISSUE TITLE
请问这是怎么回事？

### ISSUE THREAD

**Issue by tea1111980** [Mickeyto/phpVideos#2]
![000000000000000000](https://user-images.githubusercontent.com/16295097/43035481-522a6ede-8d23-11e8-835b-5784309ec296.png)

我在Windows 10 1803 17134.167 下运行的，不知道支不支持？我下的程序版本要求都是达到了的。为什么就是运行不了?

还请赐教，谢谢！

**Comment by Mickeyto** [comment]
看看你的php 版本有没有启用 curl 扩展？

**Comment by tea1111980** [comment]
好的，谢谢！我去试试

**Comment by tea1111980** [comment]
![2018-07-21](https://user-images.githubusercontent.com/16295097/43037148-a00a7bc6-8d3c-11e8-8506-12e4097823b8.png)

你看，还是不行，提示语法错误，咋整？

**Comment by tea1111980** [comment]
不好意思，我用错了命令

**Comment by tea1111980** [comment]
![2018-07-22](https://user-images.githubusercontent.com/16295097/43041670-d60f5e64-8d99-11e8-98e0-e48b3641737e.png)

全部都搞定后（如：cURL、PHP等），命令输入正确的情况下，也报错，请你看一下是怎么回事？

**Comment by Mickeyto** [comment]
以下是我测试该链接的结果。环境：Linux （php7.2.X）、Mac（php7.1.X），由于没有 win PC机，无法测试。我找朋友试试
<img width="934" alt="wx20180722-113536 2x" src="https://user-images.githubusercontent.com/20398129/43041997-727b9688-8da3-11e8-97b9-7a4ca53cea26.png">
<img width="775" alt="wx20180722-113559 2x" src="https://user-images.githubusercontent.com/20398129/43042001-7a7979f4-8da3-11e8-8b6b-f6b8cc999807.png">

**Comment by Mickeyto** [comment]
你将 Runtime\Cache 目录下的缓存文件删除了，然后再次请求一下，复制缓存文件内容提交给我

**Comment by tea1111980** [comment]
缓存文件名01：577607a6221d8a0b122a4e35912fd513
内容：a:2:{i:0;s:32:"2e3e3ff18d6211e89d19a042d48ad00a";i:1;i:1532231962;}


缓存文件名02：ed2235de7e11465d9f4632c842c00251
内容：a:2:{i:0;N;i:1;i:0;}

**Comment by tea1111980** [comment]
![02020202020202020202020](https://user-images.githubusercontent.com/16295097/43042177-ecf08ce8-8da8-11e8-814a-891a7c4f1d28.png)


![0303030303](https://user-images.githubusercontent.com/16295097/43042199-e78053f0-8da9-11e8-9595-e26f94d4bb0e.png)


我在Linux下也这样，CentOS7。
请看上图

我怀疑还是组件的问题，如：cURL 等。
但是不知道怎么处理。
问题是，我已经启用了PHP的 cURL、OpenSSL扩展了，下载方面应该没问题了。
但是还是下载不了。

**Comment by Mickeyto** [comment]
Centos7 默认的 curl 版本是 7.29 的，需要升级。我的已经升级：
rpm -ivh http://mirror.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-2-1.rhel7.noarch.rpm
yum --enablerepo=city-fan.org update curl

curl 升级之后， php 需要重新编译

**Comment by tea1111980** [comment]
![image](https://user-images.githubusercontent.com/16295097/43042566-4c538e46-8db4-11e8-9393-dd63e1ddb15b.png)

这是结果。

**Comment by Mickeyto** [comment]
今晚我修复

**Comment by tea1111980** [comment]
![image](https://user-images.githubusercontent.com/16295097/43042817-6c38ae5e-8db8-11e8-8d5f-d98d82439755.png)


这是相应的程序版本。

你有没有telegram 或者 discord ？
只是为了方便即时反馈。

**Comment by Mickeyto** [comment]
Discord：https://discord.gg/yuxfCy
